### ISSUE TITLE
Possible to detect whether the text is clamped or not

### ISSUE THREAD

**Issue by ahnpnl** [clampy-js/ngx-clampy#6]
Hi,

I have a use case that: I put `clampy` directive on my `<p>` and upon initializing the component, I want to know if the text in my `<p` is clamped or not so I can show the link `Show more`. If the text in my `<p>` isn't clamped because it doesn't exceed the width of the parent, then I don't want to show that `Show more` link.

I notice that the event `originalContent` only fires when the text in `p` is clamped. Maybe `clampy` directive can expose an event to notify the users that the text isn't clamped because it doesn't exceed the width of the parent.

I include an example from Stackblitz [here](https://stackblitz.com/edit/angular-g4e6q7)

**Comment by alexandremoore** [comment]
In version 8.0.1, I added the `isClamped` event that will emit a boolean if the content is clamped or not.
